#!/bin/sh

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# For some reason, dwm doesn't read Xresources on start up, if it was run with &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources
# For other apps (such as dunst)
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &

setxkbmap -option caps:swapescape
setxkbmap -layout us,pl,ru,ua -option grp:alt_shift_toggle
setbg &			# set the background with the `setbg` script
xcompmgr &		# xcompmgr for transparency
xset r rate 200 40 &	# Speed xrate up
unclutter &		# Remove mouse when idle
dunst-xresources &			# dunst for notifications
