require('keymappings.nvim')
require('keymappings.telescope')
require('keymappings.nvim-tree')
require('keymappings.commentary')
require('keymappings.lspconfig')
require('keymappings.vim-maximizer')
require('keymappings.vim-fugitive')
